name: purity
description: "Purity is an Arabic app that aims to enable users to transparently understand the ingredients of food products. With a simple barcode scan, you can discover nutritional facts, allergens, and chemical additivesâ€”making informed choices that are best for your health and the environment."

version: 1.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  # Add this line
  cupertino_icons: ^1.0.8
  # --------------------------------------------- #
  cached_network_image: ^3.4.1
  device_info_plus: ^12.2.0
  dartz: ^0.10.1
  dio: ^5.9.0
  easy_localization: ^3.0.8
  equatable: ^2.0.7
  firebase_core: ^4.2.0
  flutter_bloc: ^9.1.1
  flutter_downloader: ^1.12.0
  flutter_native_splash: ^2.4.7
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.1
  flutter_typeahead: ^5.2.0
  form_field_validator: ^1.1.0
  get: ^4.7.2
  get_it: ^8.2.0
  internet_connection_checker: ^3.0.1
  just_audio: ^0.10.5
  mobile_scanner: ^7.1.3
  motion_toast: ^2.14.0
  path_provider: ^2.1.5
  package_info_plus: ^9.0.0
  permission_handler: ^12.0.1
  quickalert: ^1.1.0
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/translations/
    - pubspec.yaml

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
